"""Unit tests for prompt version management."""

from __future__ import annotations

from pathlib import Path

import pytest

from src.pipeline.prompt_versioning import PromptVersionManager


def test_register_and_get_prompt(tmp_path: Path) -> None:
    manager = PromptVersionManager(str(tmp_path / "prompt_registry.json"))
    registered = manager.register_prompt(
        template="Correct: {input}",
        description="test prompt",
        version_id="v3.0.0",
    )

    loaded = manager.get_prompt("v3.0.0")

    assert loaded.version_id == registered.version_id
    assert loaded.description == "test prompt"


def test_update_metrics_and_compare_versions(tmp_path: Path) -> None:
    manager = PromptVersionManager(str(tmp_path / "prompt_registry.json"))
    manager.update_metrics("v1.0.0", {"gleu": 0.7})
    comparison = manager.compare_versions("v1.0.0", "v1.1.0")

    assert "left" in comparison
    assert "gleu" in comparison["metric_keys"]


def test_promote_and_rollback(tmp_path: Path) -> None:
    manager = PromptVersionManager(str(tmp_path / "prompt_registry.json"))
    manager.promote_prompt("v2.0.0")
    rolled_back = manager.rollback()

    assert rolled_back.version_id == "v1.1.0"


def test_export_registry_writes_file(tmp_path: Path) -> None:
    manager = PromptVersionManager(str(tmp_path / "prompt_registry.json"))
    export_path = tmp_path / "export.json"
    manager.export_registry(str(export_path))

    assert export_path.exists()
    assert '"versions"' in export_path.read_text(encoding="utf-8")


def test_duplicate_version_and_unknown_metric_updates_raise(tmp_path: Path) -> None:
    manager = PromptVersionManager(str(tmp_path / "prompt_registry.json"))
    manager.register_prompt(
        template="Correct: {input}",
        description="test prompt",
        version_id="v3.0.0",
    )

    with pytest.raises(ValueError):
        manager.register_prompt(
            template="Correct again: {input}",
            description="duplicate",
            version_id="v3.0.0",
        )

    with pytest.raises(KeyError):
        manager.update_metrics("v9.9.9", {"gleu": 0.5})


def test_autogenerated_version_and_single_history_rollback(tmp_path: Path) -> None:
    manager = PromptVersionManager(str(tmp_path / "prompt_registry.json"))
    prompt = manager.register_prompt(
        template="Correct with context: {context} {input}",
        description="auto semver",
    )
    rolled_back = manager.rollback()

    assert prompt.version_id.startswith("v")
    assert rolled_back.version_id == manager.get_active_prompt().version_id


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__]))
